### ISSUE TITLE
Aggregate preservation requests

### ISSUE THREAD

**Issue by pbinkley** [ualbertalib/pushmi_pullyu#9] opened 2017-02-23 21:58 UTC
Within HydraNorth, an ```after_save``` process will push the NOID of a changed object (and timestamp) onto a Redis queue whenever the Rails object is saved via ActiveFedora.

**Comment by murny** [comment] 2017-04-24 21:25
Oops. Didn't see this one. Duplicate of https://github.com/ualbertalib/pushmi_pullyu/issues/21. Closing issue.

**Closed by murny** 2017-04-24 21:25 UTC
Labels: duplicate
